follow_symlinks = false
palette = 'chicago95'
continuation_prompt = '[▶▶](fg:base1) '

add_newline = true
format = """
    $directory\
$fill \
${custom.sshwarn}${custom.uwu_active}${custom.uwu_inactive} \
$username\
$hostname\
$time\
$line_break\
$jobs\
\\$ """

[username]
format = "[$user]($style)"
show_always = true
style_user = 'bold fg:cyan'
style_root = 'bold fg:red'

[hostname]
disabled = false
ssh_only = true
format = '[@](fg:base0)[$hostname](bold fg:green)'
ssh_symbol = ''

[custom.sshwarn]
disabled = false
when = '[ -n "$SSH_CONNECTION" ]'
command = '[ -n "$SSH_CONNECTION" ] && echo -n "ssh"'
shell = 'sh' # makes it work on fish, nushell
format = '\[[$output](bold fg:red)\]-'

[custom.uwu_active]
disabled = false
when = '[ -n "$IN_NIX_SHELL" ] || [ -n "$DIRENV_DIR" ]'
command = 'echo -n "owo"'
shell = 'sh'
format = '\($output\)'

[custom.uwu_inactive]
disabled = false
when = '[ -z "$IN_NIX_SHELL" ] && [ -z "$DIRENV_DIR" ]'
command = 'echo -n "uwu"'
shell = 'sh'
format = '\($output\)'

[directory]
disabled = false
style = 'bold fg:yellow'
format = '[$path]($style) '
truncation_symbol = '*/'

[fill]
symbol = ' '
style = "fg:base01"

[time]
format = ' [$time]($style) '
time_format="%m-%d %R"
disabled = false
style = 'fg:base0'

[jobs]
disabled = false
style = 'bold fg:blue'
